CREATE SCHEMA IF NOT EXISTS ${silver};

CREATE TABLE IF NOT EXISTS ${silver}.load_runs(load_run_id VARCHAR PRIMARY KEY, started_at TIMESTAMP WITH TIME ZONE NOT NULL, finished_at TIMESTAMP WITH TIME ZONE, status VARCHAR NOT NULL, source_max_ingested_at TIMESTAMP WITH TIME ZONE, structures_loaded BIGINT DEFAULT(0), mappings_loaded BIGINT DEFAULT(0), messages_processed BIGINT DEFAULT(0), events_inserted BIGINT DEFAULT(0), error_message VARCHAR);

CREATE TABLE IF NOT EXISTS ${silver}.state_events(received_at TIMESTAMP WITH TIME ZONE NOT NULL, received_at_berlin TIMESTAMP NOT NULL, source_id VARCHAR NOT NULL, message_id VARCHAR NOT NULL, message_type INTEGER NOT NULL, state_uuid VARCHAR NOT NULL, state_name VARCHAR, control_uuid VARCHAR, control_name VARCHAR, control_type VARCHAR, room_uuid VARCHAR, room_name VARCHAR, category_uuid VARCHAR, category_name VARCHAR, value_numeric DOUBLE, value_text VARCHAR, value_json JSON, structure_id VARCHAR, structure_captured_at TIMESTAMP WITH TIME ZONE, structure_last_modified VARCHAR, structure_resolution VARCHAR NOT NULL, mapping_source VARCHAR, mapping_priority INTEGER, competing_best_mappings INTEGER, resolution_status VARCHAR NOT NULL, bronze_ingested_at TIMESTAMP WITH TIME ZONE NOT NULL, loaded_at TIMESTAMP WITH TIME ZONE DEFAULT(now()) NOT NULL);

CREATE TABLE IF NOT EXISTS ${silver}.state_uuid_map(structure_id VARCHAR NOT NULL, structure_captured_at TIMESTAMP WITH TIME ZONE NOT NULL, structure_last_modified VARCHAR, state_uuid VARCHAR NOT NULL, state_name VARCHAR, control_uuid VARCHAR, control_name VARCHAR, control_type VARCHAR, room_uuid VARCHAR, room_name VARCHAR, category_uuid VARCHAR, category_name VARCHAR, mapping_source VARCHAR NOT NULL, mapping_priority INTEGER NOT NULL, control_path VARCHAR, loaded_at TIMESTAMP WITH TIME ZONE DEFAULT(now()) NOT NULL);

CREATE TABLE IF NOT EXISTS ${silver}.structure_versions(structure_id VARCHAR, source_id VARCHAR, structure_captured_at TIMESTAMP WITH TIME ZONE, structure_last_modified_raw VARCHAR, structure_last_modified TIMESTAMP, payload_sha256 VARCHAR, collector_version VARCHAR, ingested_at TIMESTAMP WITH TIME ZONE, payload_bytes BIGINT, control_count BIGINT, control_object_count BIGINT, state_mapping_count BIGINT, room_count BIGINT, category_count BIGINT, PRIMARY KEY(structure_id));



CREATE VIEW IF NOT EXISTS ${silver}.current_state AS SELECT source_id, state_uuid, state_name, control_uuid, control_name, control_type, room_uuid, room_name, category_uuid, category_name, received_at AS last_received_at, received_at_berlin AS last_received_at_berlin, value_numeric, value_text, value_json, structure_id, resolution_status FROM ${silver}.state_events QUALIFY (row_number() OVER (PARTITION BY source_id, state_uuid ORDER BY received_at DESC, message_id DESC) = 1);

CREATE VIEW IF NOT EXISTS ${silver}.mapping_conflicts AS SELECT structure_id, state_uuid, count_star() AS mapping_count, count(DISTINCT ((((control_uuid || '|') || COALESCE(state_name, '')) || '|') || mapping_source)) AS distinct_meanings, min(mapping_priority) AS best_priority, string_agg(((((mapping_source || ':') || COALESCE(control_name, '?')) || '.') || COALESCE(state_name, '?')), ' | ' ORDER BY mapping_priority, control_name, state_name) AS meanings FROM ${silver}.state_uuid_map GROUP BY structure_id, state_uuid HAVING (count(DISTINCT ((((control_uuid || '|') || COALESCE(state_name, '')) || '|') || mapping_source)) > 1);

CREATE VIEW IF NOT EXISTS ${silver}.state_retention_hints AS SELECT source_id, state_uuid, any_value(state_name) AS state_name, any_value(control_name) AS control_name, any_value(control_type) AS control_type, CASE  WHEN ((lower(any_value(state_name)) IN ('total', 'totalday', 'totalweek', 'totalmonth', 'totalyear', 'totalneg', 'totalnegday', 'totalnegweek', 'totalnegmonth', 'totalnegyear'))) THEN ('meter_counter') WHEN ((lower(any_value(state_name)) IN ('actual', 'conscurr', 'gridcurr', 'gpwr'))) THEN ('live_value') WHEN ((lower(any_value(control_type)) IN ('switch', 'pushbutton', 'infoonlydigital', 'presence', 'windowmonitor', 'alarm', 'timedswitch'))) THEN ('discrete_state') ELSE 'unclassified' END AS retention_class, CASE  WHEN ((lower(any_value(state_name)) IN ('total', 'totalday', 'totalweek', 'totalmonth', 'totalyear', 'totalneg', 'totalnegday', 'totalnegweek', 'totalnegmonth', 'totalnegyear'))) THEN ('Candidate for 1-minute snapshots or threshold-based Gold aggregation') WHEN ((lower(any_value(state_name)) IN ('actual', 'conscurr', 'gridcurr', 'gpwr'))) THEN ('Retain at finer granularity in Gold') WHEN ((lower(any_value(control_type)) IN ('switch', 'pushbutton', 'infoonlydigital', 'presence', 'windowmonitor', 'alarm', 'timedswitch'))) THEN ('Model as true change events in Gold') ELSE 'Inspect semantics before aggregation' END AS gold_guidance FROM ${silver}.state_events WHERE (resolution_status ~~ 'resolved_%') GROUP BY source_id, state_uuid;

CREATE VIEW IF NOT EXISTS ${silver}.unresolved_states AS SELECT source_id, state_uuid, min(received_at) AS first_seen, max(received_at) AS last_seen, count_star() AS event_count, count(DISTINCT message_id) AS message_count, count_star() FILTER (WHERE (structure_resolution = 'no_valid_structure')) AS events_without_valid_structure FROM ${silver}.state_events WHERE (resolution_status = 'unresolved') GROUP BY source_id, state_uuid;

CREATE VIEW IF NOT EXISTS ${silver}.data_quality_summary AS (SELECT 'silver_events' AS metric, CAST(count_star() AS "DOUBLE") AS value_numeric, CAST(NULL AS VARCHAR) AS value_text FROM ${silver}.state_events) UNION ALL (SELECT 'resolved_events', CAST(count_star() FILTER (WHERE (resolution_status ~~ 'resolved_%')) AS "DOUBLE"), NULL FROM ${silver}.state_events)UNION ALL (SELECT 'ambiguous_events', CAST(count_star() FILTER (WHERE (resolution_status = 'ambiguous')) AS "DOUBLE"), NULL FROM ${silver}.state_events)UNION ALL (SELECT 'unresolved_events', CAST(count_star() FILTER (WHERE (resolution_status = 'unresolved')) AS "DOUBLE"), NULL FROM ${silver}.state_events)UNION ALL (SELECT 'resolved_percent', ((100.0 * count_star() FILTER (WHERE (resolution_status ~~ 'resolved_%'))) / "nullif"(count_star(), 0)), NULL FROM ${silver}.state_events)UNION ALL (SELECT 'unresolved_percent', ((100.0 * count_star() FILTER (WHERE (resolution_status = 'unresolved'))) / "nullif"(count_star(), 0)), NULL FROM ${silver}.state_events)UNION ALL (SELECT 'duplicate_message_state_pairs', CAST(COALESCE(sum((c - 1)), 0) AS "DOUBLE"), NULL FROM (SELECT count_star() AS c FROM ${silver}.state_events GROUP BY source_id, message_id, state_uuid HAVING (count_star() > 1)))UNION ALL (SELECT 'events_without_valid_structure', CAST(count_star() FILTER (WHERE (structure_resolution = 'no_valid_structure')) AS "DOUBLE"), NULL FROM ${silver}.state_events)UNION ALL (SELECT 'events_using_earliest_structure_fallback', CAST(count_star() FILTER (WHERE (structure_resolution = 'fallback_earliest')) AS "DOUBLE"), NULL FROM ${silver}.state_events)UNION ALL (SELECT 'mapping_conflict_uuids', CAST(count_star() AS "DOUBLE"), NULL FROM ${silver}.mapping_conflicts)UNION ALL (SELECT 'valid_structures', CAST(count_star() AS "DOUBLE"), NULL FROM ${silver}.structure_versions)UNION ALL (SELECT 'invalid_structures_excluded', CAST(((SELECT count_star() FROM ${bronze}.structures) - count_star()) AS "DOUBLE"), NULL FROM ${silver}.structure_versions)UNION ALL (SELECT 'min_event_time_utc', NULL, CAST(min(received_at) AS VARCHAR) FROM ${silver}.state_events)UNION ALL (SELECT 'max_event_time_utc', NULL, CAST(max(received_at) AS VARCHAR) FROM ${silver}.state_events);